"""
Standard disclaimer template for all financial reports.
This ensures consistent legal protection across all report types.
"""

STANDARD_DISCLAIMER = """
IMPORTANT DISCLAIMER: NOT FINANCIAL ADVICE

The information contained in this report is for informational and educational purposes only. It is not intended to be, and should not be construed as, financial advice, investment advice, trading advice or any other form of advice. You should not make any financial, investment, trading or other decisions based solely on the information presented in this report without undertaking independent due diligence and consultation with a professional broker or financial advisor.

Past performance is not indicative of future results. The investments and strategies discussed in this report may not be suitable for all investors and are not guaranteed to achieve the projected returns. All investing involves risk, including the possible loss of principal. Diversification does not ensure a profit or protect against a loss in a declining market.

The projections or other information generated by this report regarding the likelihood of various investment outcomes are hypothetical in nature, do not reflect actual investment results, and are not guarantees of future results. Actual results may vary significantly.

ISO Financial is not a registered investment advisor, broker-dealer, or financial institution. We are not qualified to give financial advice, and nothing in this report should be construed as advice regarding the value of any security or the advisability of investing in, purchasing, or selling any security.

Cryptocurrency, digital assets, and alternative investments carry significant risks, including but not limited to volatility, lack of regulation, and potential complete loss of value. These risks are heightened for NFTs and other emerging asset classes that may lack liquidity, established valuation methods, or regulatory oversight.

You are solely responsible for evaluating the risks and merits of any investment decisions. We strongly advise you to conduct thorough research and consult with qualified financial, legal, and tax professionals before making any investment decisions.

By using this report, you acknowledge that you are aware of the risks involved in investing and agree that ISO Financial will not be held liable for any losses, damages, or expenses that may arise from your investment decisions.
"""

def get_standard_disclaimer() -> str:
    """
    Return the standard disclaimer text for financial reports
    
    Returns:
        String containing the full disclaimer text
    """
    return STANDARD_DISCLAIMER